-- CreateTable
CREATE TABLE `Pegawaii` (
    `id` VARCHAR(191) NOT NULL,
    `nip` VARCHAR(191) NOT NULL,
    `nama` VARCHAR(191) NOT NULL,
    `tempatLahir` VARCHAR(191) NULL,
    `tanggalLahir` DATETIME(3) NULL,
    `jenisKelamin` VARCHAR(191) NULL,
    `agama` VARCHAR(191) NULL,
    `alamat` VARCHAR(191) NULL,
    `noTelp` VARCHAR(191) NULL,
    `jabatan` VARCHAR(191) NOT NULL,
    `pangkat` VARCHAR(191) NULL,
    `golonganRuang` VARCHAR(191) NOT NULL,
    `tmtGolongan` DATETIME(3) NULL,
    `unitKerja` VARCHAR(191) NULL,
    `masaKerja` VARCHAR(191) NULL,
    `tglMasaKerja` DATETIME(3) NULL,
    `gajiPokok` INTEGER NULL,
    `tmtPangkat` DATETIME(3) NULL,
    `pendidikanAkhir` VARCHAR(191) NULL,
    `statusPegawai` VARCHAR(191) NOT NULL DEFAULT 'AKTIF',
    `fotoUrl` VARCHAR(191) NULL,
    `bidangId` VARCHAR(191) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `Pegawaii_nip_key`(`nip`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
