-- AlterTable
ALTER TABLE `cuti` MODIFY `status` ENUM('DRAFT', 'MENUNGGU_ATASAN_1', 'DITOLAK_ATASAN_1', 'MENUNGGU_ATASAN_2', 'DITOLAK_ATASAN_2', 'MENUNGGU_ADMIN', 'DISETUJUI', 'DITOLAK') NOT NULL DEFAULT 'DRAFT';
